### ISSUE TITLE
Upgrading to the latest version

### ISSUE THREAD

**Issue by esebese** [LDO-CERT/orochi#1021]
I am currently using v1.3.1 and would like to upgrade to the v2.1.1 without losing the current configuration, rules, dumps etc. How can I achieve that?

**Comment by garanews** [comment]
- We do not manage the migration of ElasticSearch and PostgreSQL releases, so you should upgrade those manually or pin with your current version. If it is a minor upgrade (example from 8.9 to 8.17 it should be fine).
- Data contained in PostgreSQL support migrations so when the new service start, all migrations will be applied.
- The only changes regard additional data on dumpled files, for example virus total results on pslist dumped files: we removed from PostgreSQL and now are stored in json files. No migration for that.

We suggest you to peform a dump of PostgreSQL with pg_dump.

Write for any question!

**Comment by garanews** [comment]
New version looks very nice! And there is support of symbols upload!
![image](https://github.com/LDO-CERT/orochi/assets/16938405/cc04cf82-837a-4a60-9191-19af15b7e08e)

**Comment by esebese** [comment]
Thanks!
