### ISSUE TITLE
Custom logo in the login page

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#1083]
Maybe here:
![image](https://github.com/LDO-CERT/orochi/assets/16938405/d10600a0-e6fd-4b66-97b9-e38e88616781)

Or here:
![image](https://github.com/LDO-CERT/orochi/assets/16938405/0aa4284f-468e-447c-bc49-0d20def7e524)

**Comment by dadokkio** [comment]
![image](https://github.com/user-attachments/assets/828bb3c7-ad66-49f1-a932-551b76fcaef0)
