### ISSUE TITLE
bug: API return all data 

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#139]
Instead return data of selected dump, it returns data of other dumps:
![immagine](https://user-images.githubusercontent.com/16938405/96599702-7e93d280-12f0-11eb-9e9f-8b57d8f76010.png)

**Comment by dadokkio** [comment]
Fixed in https://github.com/LDO-CERT/orochi/commit/fdb083ef759970c8961c1de64eba7d3e0e683afa 
There is now a /results/ endpoint with all result for a dump, link are not generated in dump serialization
