### ISSUE TITLE
Not able to get any output from plugins

### ISSUE THREAD

**Issue by mflage** [LDO-CERT/orochi#169]
Hi!

I have uploaded the dump, created the index. All good so far. Then I want to run some of the plugins. None of them return any data. When looking at the output I see two buttons to the top right, one indicating a rehash/refresh (yellow reload) and the other is a red (btn btn-sm btn-outline-danger btn-log) and when clicking that I only get the text: "Windows kernel symbols" in red. I guess this means that there's something wrong with the Windows kernel symbols (maybe create a more informative error message...?). I ran symbols_sync after installation:

```
Starting orochi_postgres ... 
Starting orochi_mailhog ... done
PostgreSQL is available
/usr/local/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Local hash: None
Remote hash: {'windows.zip': '7ae5225fa542d043af31fb3b9f5863de', 'mac.zip': '8b111c0ea5a1dd9309cf7e79ec2c6816', 'linux.zip': '029662b9e190e8d72b7b09da19015808'}
Hashes for windows.zip are different - downloading
Removing path /src/volatility/volatility/symbols/windows.
Starting download of zip symbols windows.zip.
Download of zip symbols completed for windows.zip.
Hashes for mac.zip are different - downloading
Removing path /src/volatility/volatility/symbols/mac.
Starting download of zip symbols mac.zip.
Download of zip symbols completed for mac.zip.
Hashes for linux.zip are different - downloading
Removing path /src/volatility/volatility/symbols/linux.
Starting download of zip symbols linux.zip.
Download of zip symbols completed for linux.zip.
Updating local hashes
Clearing cache
```
And if I run it now:

```
$ docker-compose run --rm django python manage.py symbols_sync
Starting orochi_mailhog ... done
PostgreSQL is availables ... done
/usr/local/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Local hash: {'windows.zip': '7ae5225fa542d043af31fb3b9f5863de', 'mac.zip': '8b111c0ea5a1dd9309cf7e79ec2c6816', 'linux.zip': '029662b9e190e8d72b7b09da19015808'}
Remote hash: {'windows.zip': '7ae5225fa542d043af31fb3b9f5863de', 'mac.zip': '8b111c0ea5a1dd9309cf7e79ec2c6816', 'linux.zip': '029662b9e190e8d72b7b09da19015808'}
Hashes for windows.zip are equal - skipping
Hashes for mac.zip are equal - skipping
Hashes for linux.zip are equal - skipping
```

When looking at the output from the different workers I can see quite a lot of these warning messages:

```
worker01_1   | WARNING 2020-11-11 08:26:06,107 __init__ 367 139935630337792 Automagic exception occurred: TypeError: super() argument 1 must be type, not Enumeration
```

**Comment by garanews** [comment]
Hello, I have some question about it: because probably is not easy share the memory image (due to size/privacy), what about if you run volatility3 locally against your image: do you get some result? 
If no experience with volatility tool just follow quick quide:
https://github.com/volatilityfoundation/volatility3#quick-start 
Then download manually symbols and put inside volatility/symbols folder and run some plugin as described there. 
And would know more about image: how did you take it (which tool) and what OSis?

**Comment by mflage** [comment]
Seems like I have more or less the same problem here as well:

```
$ ./vol.py -f test.dmp windows.info.Info
Volatility 3 Framework 2.0.0-beta.1
WARNING  volatility.framework.plugins: Automagic exception occurred: TypeError: super() argument 1 must be type, not Enumeration                   

Unsatisfied requirement plugins.Info.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']
```

This is from the DumpIt tool.

**Comment by garanews** [comment]
This from one side is a good news: we do not reinvented the wheel, we just created collaborative gui for volatility.
From other side, need to know more about the image, so which OS is (win10 x64, etc...) what tool did you use to take memory dump.. Those are more volatility questions but happy to help here.

**Comment by garanews** [comment]
Ah in your local install ensure you downloaded windows symbols and put inside volatility symbols folder

**Comment by dadokkio** [comment]
Ok, I tried the latest volatility commit on my machine and I can confirm that info plugin is returning errors:
![image](https://user-images.githubusercontent.com/355183/98792666-1f187680-2407-11eb-9438-aa316d17e3b1.png)

Can you please try another plugin (like pslist in my screen) also on orochi to check if everything is ok?

**Comment by dadokkio** [comment]
MEanwhile I've opened an issue on volatility repo for this plugin :+1:

**Comment by dadokkio** [comment]
The issue on volatility repo has been closed and I was able to run the plugin without issue.

**Comment by garanews** [comment]
Hi @mflage can you provide any feedback?
