### ISSUE TITLE
Django docker isn't working

### ISSUE THREAD

**Issue by Nicole1122** [LDO-CERT/orochi#188]
Hey, I've followed the steps listed under the installation process, and when I ran the "docker-compose up" everything worked fine other than the Django docker. It exited immediately.
I ran "docker logs orochi_django" to check why might it exited, and I saw this:
![Capture](https://user-images.githubusercontent.com/67701501/101760853-19847e00-3ae4-11eb-83c2-9b33e437bfd8.PNG)
Can you help me understand why it happened and fix this issue?

**Comment by dadokkio** [comment]
Sorry, was my fault.
We are working to add automatic symbol download (actually in develop under banner_support branch) and I added new field in admin.
The latest pull should resolve the issue.

**Comment by garanews** [comment]
Confirm now is working
![image](https://user-images.githubusercontent.com/16938405/102072529-4eeddc00-3e02-11eb-982e-afbc0de7a1e7.png)
