### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by Annerr** [LDO-CERT/orochi#191]
Hi, I attempted to create a virtual machine containing the Orochi package, and then move it to a no-internet environment.
When I opened the web interface in there, everything was kinda messed up, the logo was on top of everything and well, it didn’t look as well as it did before.
Is there any chance for a pull that requires no internet connection to run after it has been downloaded?

**Comment by dadokkio** [comment]
I make a new pull with all css/js available offline. Can you give it a try?
Thanks.
