### ISSUE TITLE
Unsatisfied results

### ISSUE THREAD

**Issue by Annerr** [LDO-CERT/orochi#192]
Hey, first I want to say thanks for the quick answer on the other subject.
Something else popped up right now. I tried to upload a 1gb compressed memory to test orochi (a memory dump that I ran volatility plugins on it before, and worked fine) and it didn’t turn out so well. I added a picture containing the results.
Where may I have gone wrong?
Thanks in advance (:
![image](https://user-images.githubusercontent.com/75938925/102062349-48a93100-3dfd-11eb-89a8-8f493f856115.jpg)

**Comment by dadokkio** [comment]
Ok, I see that the image is windows and you have full list of plugin so I suppose that also symbols have been properly downloaded. right?
If not in the top right corner of the admin there is an update symbols link (you need network connection) or if you want to see log you can use docker command: `docker-compose run --rm django python manage.py symbols_sync`
Usually unsatisfied error is related to missing symbols, but if this is not the reason we'll investigate.

**Comment by garanews** [comment]
![orochi_plugin](https://user-images.githubusercontent.com/16938405/102076891-c0c92400-3e08-11eb-94df-0c6cd432597b.png)
@Annerr check screenshot, everything is ok.
Before load any memory dump, ensure you have updated(loaded) volatility plugins (you know windows.plist,...) and volatility symbols (windows.zip,...)
We provide command line commands (you can see on right of screenshot) trat can be also run from admin GUI  (you can see on left of screen).
In the middle of the screen you see the memory dump just uloaded and pslist output after execution.
Let me know if we can close this issue.
