### ISSUE TITLE
Create django super user in a docker container without executing manage.py manually

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#222]
In swarm environments is not possible to launch  manage.py command to create super user.
To avoid issues in swarm envs it would be useful to have the django super admin created automatically:
https://stackoverflow.com/questions/30027203/create-django-super-user-in-a-docker-container-without-inputting-password

**Comment by dadokkio** [comment]
Added admin user on creation with migration.
Default password admin, default validated email admin@orochi.local.
