### ISSUE TITLE
autorefresh of status brings to first page

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#251]
When working on plugin result of multiple images, if there is one plugin still running, the autorefresh brings you to page 1 every 5 secs.
You have to deselect the image where plugin is still running in order to work with current results.
In the picture, windows_02 is still running and causes the autorefresh:

![image](https://user-images.githubusercontent.com/16938405/107924275-fc9c7900-6f72-11eb-85f6-131effa05ebe.png)

**Comment by dadokkio** [comment]
added an autorefresh setting in the navbar. If it's set to false it'll not update the main gui.
It uses localstorage to remember your selection between sessions.

![image](https://user-images.githubusercontent.com/355183/107930648-8cdebc00-6f7b-11eb-8d24-ee6e2215b06a.png)
