### ISSUE TITLE
Build issue w/ go

### ISSUE THREAD

**Issue by jasonblanks** [LDO-CERT/orochi#270]
Have you run across this building?

Step 10/29 : WORKDIR /
 ---> Using cache
 ---> 4f03ca912973
Step 11/29 : RUN git clone https://github.com/volatilityfoundation/dwarf2json.git
 ---> Using cache
 ---> 146c68cb85fc
Step 12/29 : WORKDIR /dwarf2json
 ---> Using cache
 ---> e4a706aa7105
Step 13/29 : RUN go build
 ---> Running in 3d092d345267
go: finding github.com/spf13/pflag v1.0.5
go: downloading github.com/spf13/pflag v1.0.5
# github.com/volatilityfoundation/dwarf2json
./dwarf.go:108:15: d.AddSection undefined (type *dwarf.Data has no field or method AddSection)
note: module requires Go 1.13ERROR: Service 'django' failed to build: The command '/bin/sh -c go build' returned a non-zero code: 2

**Comment by dadokkio** [comment]
I can confirm the error, seems that the latest change in dwarf go1.13 is required.
I've updated dockerfile to download go (1.15) before building dwarf similar to what I was doing in yara branch.
