### ISSUE TITLE
FR: Yara rules management

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#28]
TODO LIST:
- [x] models
- [x] create custom ruleset per user at creation
- [x] admin to manage ruleset/rule
- [x] download and parse rulesets list from awesome
- [x] clone or pull repo of rulesets
- [x] user page to upload/delete custom rule to his ruleset
- [x] user page to create custom rules from available rulesets
- [x] delete, publish custom rules
- [x] download custom rules
- [x] add a command to create a default with all rules from admin
- [x] make yarascan plugin use default rule if no other file are selected
- [x] add a default rule in website.rule that is run by default if automatic
- [x] test compile rule in parallel or in separated task
- [x] compile only new rule when pulling repos
- [x] show more than 100 entries per page (like 1k, 10k)
- [x] add help for elastic syntax
- [x] add elastic syntax to search
- [x] edit user rules 
- [x] copy server rules under user rules
- [x] search text inside rules
- [x] view selected rule (included system rules)
- [x] create documentation

**Comment by garanews** [comment]
I am not able to build file when selected 1k rules. 
Was trying to select all icewater rules: have to select 100 (only) per page so having like 130 pages to do select all and go next.
I stopped at page 10 and tried to build: nothing happened.
Tried with 500 and it works.
Goal is to be able to select all icewater rules and build, added 2 additional item in todo list :)

**Comment by garanews** [comment]
latest commit  ( 61083e89fcadbc45453e118dd098a736ccbfc324  ) solve previous issues.
Now addes some more requerst, like search inside rules/ view rules/ edit rules ;)

**Comment by dadokkio** [comment]
branch elastic_rules add rules in elastic. 
This resolve: 
- search in rule text
- enable elastic languages to perform complex queries
- check git diffs to compile or delete only updated rules

**Comment by garanews** [comment]
Evaluate use of [plyara](https://github.com/plyara/plyara) saving output in ES
