### ISSUE TITLE
manage windows.vadyarascan.VadYaraScan as yarascan.YaraScan

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#359]
Currently starred rules can be assigned by default only to yarascan.YaraScan.
Add support for windows.vadyarascan.VadYaraScan because at the moment only manual upload is supported.

**Comment by dadokkio** [comment]
Added in: https://github.com/LDO-CERT/orochi/commit/33cd18c5a5c79510c24f3f3d0e240d11d1769eb5

**Comment by garanews** [comment]
Thanks it works
![image](https://user-images.githubusercontent.com/16938405/121769843-328aec00-cb66-11eb-9457-dc01e7c65e07.png)

![image](https://user-images.githubusercontent.com/16938405/121769820-0ec7a600-cb66-11eb-8a99-75fc2d462598.png)
