### ISSUE TITLE
Improve path flexibility for local import (non-GUI dump uploads)

### ISSUE THREAD

**Issue by cr-jimhung** [LDO-CERT/orochi#451]
I've been looking at ways I can integrate Orochi into our analysis team's workflow and one ideal requirement would be to make dumps available via mounted GCS bucket for Orochi to consume. This is to minimise the number of copy operations on large numbers of dumps (as they will land in the buckets during our collection workflow) and reduce the amount of storage required in the Orochi service instance.

I modified the docker-compose.yml to expose the local gcsfuse mountpoint as the media_path named volume and managed the permissions to make sure the containers could access the files in the bucket. Unfortunately, when I try and issue the API request to ingest the dumps, I get this error:

```
curl -X POST "http://127.0.0.1:8000/api/dumps/import_local/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -H  "X-CSRFToken: <SNIP>" -F "filepath=/media/uploads/foo/bar.raw" -F "name=bar.raw" -F "operating_system=Windows"

OSError at /api/dumps/import_local/
[Errno 18] Invalid cross-device link: '/media/uploads/foo/bar.raw' -> '/media/uploads/bar.raw'
```

My guess is that the Path.rename() call at https://github.com/LDO-CERT/orochi/blob/b1c93086b57afefacef65d7fd7f68f934ddd0a2b/orochi/website/api/views.py#L155-L159 is the reason (as the gcsfuse mount is at /media/uploads/foo, so /media/uploads is on a physically different FS).

Is there any reason that the dumps need to strictly be under /media/uploads/* or could this be made more flexible to allow for the dumps to remain in their location supplied in the filepath arg?

**Comment by garanews** [comment]
@cr-jimhung 
under
.envs/.local/.django
you can now set

LOCAL_UPLOAD_PATH=/media/uploads
then put images there (with scp or whatever) and then browse with UI

![image](https://github.com/LDO-CERT/orochi/assets/16938405/a286cc0d-b4a4-4b4e-ab0a-03e6c891fa38)
