### ISSUE TITLE
Bookmarked query follow other plugin and images

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#463]
- visualize any plugin result
- do a query to find something
- add it to bookmarks
- switch plugin result, selecting another one
- the search fields remain populated with previous bookmarked query

This doesn't happen doing queries, it happens after bookmarking the query.
Workaround is remove the query from url.

**Comment by dadokkio** [comment]
fixed in https://github.com/LDO-CERT/orochi/commit/8adb4c282b8786d902fa17f9f325779ad7b0bab8
