### ISSUE TITLE
Issues with Complaints about no space when there is plenty

### ISSUE THREAD

**Issue by CyberKaizen** [LDO-CERT/orochi#811]
I'm having an issue where docker-compose up doesn't work due to some check for space stating there is no space available.

However, I know this is false because there is 500GB thin provisioned assigned to it and it is only using 30GB.

Anyway, to fix the scripts or make some changes to resolve this issue so that it can be ran on an ESXi host guest VM?
<img width="948" alt="image" src="https://user-images.githubusercontent.com/78124503/199868133-cb1991c8-df1c-4c55-a258-b44cbb12278c.png">

**Comment by garanews** [comment]
What is your current system setup? 
Was you running other docker images on that machine? If yes and not using anymore, you can prune, have a look here: https://linuxhint.com/fix-docker-no-device-space-left-error/

**Comment by CyberKaizen** [comment]
I gave that a shot, but no dice. Got any other ideas?

**Comment by garanews** [comment]
Need more info about server, like output of some command:

```df -h```
![df](https://user-images.githubusercontent.com/16938405/202752888-ef554d40-c823-4cc1-a450-4c1440799618.png)

```sudo docker system df -v```
![df-v](https://user-images.githubusercontent.com/16938405/202754216-3a5ab922-79fa-4731-bf12-5dab427c0aa1.png)


```docker -v && docker-compose -v ```
![docker version](https://user-images.githubusercontent.com/16938405/202754544-0d4a00a5-edee-42d8-b8e2-4d5924dc09da.png)

**Comment by CyberKaizen** [comment]
😭 I figured it out! It was something very basic and dumb!
It had something to do with how I configured my VM templates on the ESXi Host. Rookie mistake.

The error about space issues was valid.
