### ISSUE TITLE
server side table generation

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#975]
If some plugin (example  linux.proc.Maps) return large number of data (example more than 10000 rows), generating datatable at client side could take too much time.
The table generation should be done at server side.

Created branch dj to work on this.

Current behavior and issues:
- the search now work if terms match exactly the data, for partial searches need add * to search term
- search on additional generated data (such as md5) is not searchable
- happened that executing twice the windows.pslist plugin with dump caused the following error:
```packages/django/db/backends/utils.py", line 100, in _execute with self.db.wrap_database_errors: File "/opt/conda/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/opt/conda/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute return self.cursor.execute(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ django.db.utils.IntegrityError: duplicate key value violates unique constraint "website_extracteddump_path_key" DETAIL: Key (path)=(/media/f10a1a0a-a0b3-11ee-ae63-0242ac12000a/windows.pslist.PsList/356.smss.exe.0x48580000.dmp) already exists. ```

**Comment by dadokkio** [comment]
todo: add sorting for non generated columns
